# Generated by Django 4.2 on 2024-04-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfers_unite_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
