# Generated by Django 4.2 on 2024-04-07 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('golfers_unite_app', '0003_scorecard_holes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='date_played',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
