# Generated by Django 4.2 on 2024-04-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfers_unite_app', '0004_alter_scorecard_date_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
