# Generated by Django 4.2 on 2024-04-27 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfers_unite_app', '0004_alter_scorecard_date_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.PositiveIntegerField()),
                ('par', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('swing_score', models.PositiveIntegerField()),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='golfers_unite_app.scorecard')),
            ],
        ),
    ]
